#!/usr/bin/env node
/**
 * Generate the reference docs from the source of truth.
 *
 * Two things are generated: docs/rules.md in full, and the supported-language
 * table inside docs/languages.md. Both are pages people land on from a CI
 * annotation or a README claim, so they have to be right — and the only way to
 * guarantee that is to never write them by hand. `npm run docs:check`
 * re-generates into memory and fails when the committed file differs, which
 * makes stale docs a red build instead of a surprise for a reader.
 *
 * The language table matters for a second reason: the README advertises a
 * number of supported languages, and that number changes every time someone
 * contributes a pack. Generated, it cannot drift.
 *
 * Run after `npm run build` (it reads dist/).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { LANGUAGES } from "../dist/languages/index.js";
import { catalog } from "../dist/rules/index.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const target = join(root, "docs", "rules.md");
const languagesDoc = join(root, "docs", "languages.md");

const BEGIN = "<!-- BEGIN:languages -->";
const END = "<!-- END:languages -->";

/** Scripts, spelled the way a reader would name them rather than internally. */
const SCRIPT_NAMES = {
  latin: "Latin",
  greek: "Greek",
  cyrillic: "Cyrillic",
  hebrew: "Hebrew",
  arabic: "Arabic",
  devanagari: "Devanagari",
  brahmic: "Brahmic",
  thai: "Thai",
  han: "Han",
  kana: "Kana",
  hangul: "Hangul",
};

function languageTable() {
  const rows = LANGUAGES.map((pack) => {
    const scripts = pack.scripts.map((s) => SCRIPT_NAMES[s] ?? s).join(", ");
    // Only some languages make the assistant-voice distinction cleanly enough
    // for `description-third-person` to be worth running.
    const voice = pack.firstPerson?.length ? "✅" : "—";
    return `| \`${pack.code}\` | ${pack.name} | ${pack.endonym} | ${scripts} | ${pack.triggerSignals.length} | ${voice} |`;
  });
  return [
    BEGIN,
    "",
    `**${LANGUAGES.length} languages.**`,
    "",
    "| Code | Language | | Script | Trigger phrasings | Assistant-voice check |",
    "| --- | --- | --- | --- | :---: | :---: |",
    ...rows,
    "",
    "`Code` is what you write in `x-skillcheck.lang`. `Trigger phrasings` counts the",
    "patterns `when-to-use` recognizes as saying *when* a skill applies.",
    "",
    END,
  ].join("\n");
}

function renderLanguagesDoc() {
  const current = readFileSync(languagesDoc, "utf8");
  const start = current.indexOf(BEGIN);
  const end = current.indexOf(END);
  if (start === -1 || end === -1) {
    console.error(`docs/languages.md is missing its ${BEGIN} / ${END} markers`);
    process.exit(1);
  }
  return current.slice(0, start) + languageTable() + current.slice(end + END.length);
}

function fence(text) {
  return ["```yaml", text, "```"].join("\n");
}

function render() {
  const out = [];
  out.push("<!-- Generated by `npm run docs` from src/rules/. Do not edit by hand. -->");
  out.push("");
  out.push("# Rule reference");
  out.push("");
  out.push(
    `${catalog.length} checks. Every one of them maps to a documented way a skill fails — nothing here is style for style's sake.`,
  );
  out.push("");
  out.push("| Rule | Fixable | Checks |");
  out.push("| --- | :---: | --- |");
  for (const rule of catalog) {
    out.push(`| [\`${rule.id}\`](#${rule.id}) | ${rule.fixable ? "✅" : ""} | ${rule.summary} |`);
  }
  out.push("");
  out.push("Turn any rule off, or change its severity, in `skillcheck.config.json`:");
  out.push("");
  out.push('```json\n{ "rules": { "body-size": "off", "when-to-use": "warn" } }\n```');
  out.push("");
  out.push("Or for a single skill, in its own frontmatter:");
  out.push("");
  out.push("```yaml\nx-skillcheck:\n  disable: [when-to-use]\n```");
  out.push("");
  out.push("---");
  out.push("");

  for (const rule of catalog) {
    out.push(`## ${rule.id}`);
    out.push("");
    out.push(`> ${rule.summary}`);
    out.push("");
    if (rule.fixable) {
      out.push("**Fixable** — `skillcheck --fix` repairs the mechanical cases.");
      out.push("");
    }
    out.push(rule.docs.why);
    out.push("");
    if (rule.docs.bad) {
      out.push("**Trips on**");
      out.push("");
      out.push(fence(rule.docs.bad));
      out.push("");
    }
    if (rule.docs.good) {
      out.push("**Passes**");
      out.push("");
      out.push(fence(rule.docs.good));
      out.push("");
    }
    if (rule.options?.length) {
      out.push("**Options**");
      out.push("");
      out.push("| Option | Type | Default | Meaning |");
      out.push("| --- | --- | --- | --- |");
      for (const opt of rule.options) {
        out.push(`| \`${opt.name}\` | ${opt.type} | \`${JSON.stringify(opt.default)}\` | ${opt.description} |`);
      }
      out.push("");
      out.push(
        `\`\`\`json\n{ "options": { "${rule.id}": { ${rule.options.map((o) => `"${o.name}": ${JSON.stringify(o.default)}`).join(", ")} } } }\n\`\`\``,
      );
      out.push("");
    }
    out.push(`\`skillcheck explain ${rule.id}\` prints this from the terminal.`);
    out.push("");
  }

  return `${out.join("\n").trimEnd()}\n`;
}

const outputs = [
  { file: target, label: "docs/rules.md", content: render() },
  { file: languagesDoc, label: "docs/languages.md", content: renderLanguagesDoc() },
];

if (process.argv.includes("--check")) {
  let stale = false;
  for (const { file, label, content } of outputs) {
    let current = "";
    try {
      current = readFileSync(file, "utf8");
    } catch {
      console.error(`${label} is missing — run \`npm run docs\``);
      process.exit(1);
    }
    if (current !== content) {
      console.error(`${label} is out of date — run \`npm run docs\` and commit the result`);
      stale = true;
    }
  }
  if (stale) process.exit(1);
  console.log(`${outputs.map((o) => o.label).join(" and ")} are up to date`);
} else {
  for (const { file, content } of outputs) writeFileSync(file, content);
  console.log(`wrote docs/rules.md (${catalog.length} rules)`);
  console.log(`wrote docs/languages.md (${LANGUAGES.length} languages)`);
}
